### ISSUE TITLE
What does it do?

### ISSUE THREAD

**Issue by n074v41l4bl34u** [PHeonix25/fgitvis#1]

**Comment by PHeonix25** [comment]
I'll add some more information to the README about the intent and the usage instructions, but basically **we wanted to run some commands on a local GitHub repo to get some aggregated stats, and chart the results**.

I've typed up a blog post about the background [over here](https://hermens.com.au/2017/05/20/Making-fgitvis/)

I hope that makes it clear enough for now - please feel free to re-open the issue if you'd like more info, or feel free to make a PR if you have some ideas about how we could improve it.
